# Generated by Django 4.1 on 2022-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
