# Generated by Django 4.1 on 2022-10-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_alter_puzzlemodel_correct_variations_and_more'),
        ('authentication', '0005_remove_userdata_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='sets_practiced',
            field=models.ManyToManyField(to='puzzles.setmodel'),
        ),
    ]
