# Generated by Django 4.1 on 2022-10-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userdata_sets_practiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='total_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
