# Generated by Django 4.1 on 2022-09-11 18:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_remove_customuser_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
                ('lastCompletion', models.DateField(default=datetime.date(2022, 9, 10))),
            ],
        ),
    ]
