# Generated by Django 4.1 on 2022-09-24 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskmodel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='lastCompletion',
            field=models.DateField(default=datetime.date(2022, 9, 23)),
        ),
    ]
