# Generated by Django 4.1 on 2022-10-01 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskmodel_lastcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='lastCompletion',
            field=models.DateField(default=datetime.date(2022, 9, 29)),
        ),
    ]
