# Generated by Django 4.1 on 2022-09-27 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmodel',
            name='last_opened',
            field=models.DateField(default=datetime.date(2022, 9, 27)),
        ),
    ]
