# Generated by Django 4.1 on 2022-09-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_alter_setmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodel',
            name='id',
            field=models.SlugField(allow_unicode=True, default=None, primary_key=True, serialize=False),
        ),
    ]
