# Generated by Django 4.1 on 2022-10-01 01:14

from django.db import migrations, models
import puzzles.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_alter_setmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodel',
            name='id',
            field=models.SlugField(allow_unicode=True, default=puzzles.models.generate_random_id, primary_key=True, serialize=False),
        ),
    ]
