# Generated by Django 4.1 on 2022-10-03 01:35

from django.db import migrations, models
import puzzles.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_alter_setmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlemodel',
            name='correct_variations',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='puzzlemodel',
            name='fen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setmodel',
            name='id',
            field=models.SlugField(default=puzzles.models.generate_random_id, primary_key=True, serialize=False),
        ),
    ]
